"""add_min_paid_threshold_to_raffles

Revision ID: cb4cd4186bc9
Revises: e04de806546e
Create Date: 2026-05-20 16:34:10.482822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb4cd4186bc9'
down_revision: Union[str, None] = 'e04de806546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'raffles',
        sa.Column('min_paid_threshold', sa.Integer(), nullable=False, server_default='200'),
    )
    # Una vez backfilled, removemos el server_default para que el default lo
    # gobierne la app (mapped_column default=200).
    op.alter_column('raffles', 'min_paid_threshold', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'min_paid_threshold')
    # ### end Alembic commands ###
