"""add_commission_tiers_to_raffles

Revision ID: e04de806546e
Revises: e836429aca19
Create Date: 2026-05-20 14:37:56.806702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e04de806546e'
down_revision: Union[str, None] = 'e836429aca19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffles', sa.Column('commission_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'commission_tiers')
    # ### end Alembic commands ###
